# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  fastapi-app:
    image: fastapi
    environment:
      - FASTAPI_DATA_MONGODB_URI=mongodb://fastapi-mongodb:27017
      - FASTAPI_DATA_MONGODB_DATABASE=FastAPI
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
  fastapi-mongodb:
    image: mongo:4.4.12
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:27017:27017
    # volumes:
    #   - ~/volumes/fastapi/MyApp/mongodb/:/data/db/

